spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mycake
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db/changelog-master.yaml
    enabled: true
    rollback-file: /home/farozy/Projects/liquibase/rollback.yaml