version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mycake
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    ports:
      - "5432:5432"

  app:
    image: application_core:latest
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mycake
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_LIQUIBASE_ENABLED: true
    volumes:
      - ./liquibase/rollback.yaml:/home/farozy/Projects/liquibase/rollback.yaml
    networks:
      - mynetwork
    ports:
      - "8080:8080"